version: '3.8'

services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./backend/services/eureka-server
      dockerfile: Dockerfile
    image: eurekaserver:latest
    restart: always
    ports:
      - "8761:8761"
    networks:
      - flareye_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api-gateway:
    build:
      context: ./backend/services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - flareye_network

  authentication-service:
    build:
      context: ./backend/services/authentication-service
      dockerfile: Dockerfile
    container_name: authentication-service
    restart: always
    # ports:
    #   - "8081:8081"
    expose:
      - "8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://authentication-postgres:5432/authentication_db
      SPRING_DATASOURCE_USERNAME: authentication_user
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      eureka-server:
        condition: service_healthy
      authentication-postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - flareye_network

  authentication-postgres:
    image: postgres:latest
    container_name: authentication_postgres
    restart: always
    environment:
      POSTGRES_DB: authentication_db
      POSTGRES_USER: authentication_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - authentication_postgres_data:/var/lib/postgresql/data
    networks:
      - flareye_network

  redis:
    image: redis:latest
    container_name: flareye_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - flareye_network

networks:
  flareye_network:
    driver: bridge

volumes:
  authentication_postgres_data: