server:
  port: 8081

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://authentication-postgres:5432/authentication_db
    username: authentication_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      authorizationserver:
        issuer-uri: http://authentication-service:8081  # localhost yerine servis adı
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:8081
  data:
    redis:
      host: flareye_redis  # Docker-compose'daki Redis container adı
      port: 6379

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: authentication-service
    prefer-ip-address: false